# Generated by Django 2.2.3 on 2020-03-25 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0021_auto_20200325_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_entities', to='pokemon_entities.Pokemon', verbose_name='Покемон'),
        ),
    ]
